//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupperMarket3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributesPrices
    {
        public int AttributesPriceID { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<double> Price { get; set; }
        public bool Active { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual Product Product { get; set; }
    }
}
