//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupperMarket3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AttributesPrices = new HashSet<AttributesPrices>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int IdProduct { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceSale { get; set; }
        public Nullable<int> CateGoryID { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> Discount { get; set; }
        public string Thumb { get; set; }
        public string Video { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> BestSellers { get; set; }
        public Nullable<bool> HomeFlag { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Tag { get; set; }
        public string Alias { get; set; }
        public string MetaKey { get; set; }
        public string MetaDesc { get; set; }
        public Nullable<int> UnitslnStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributesPrices> AttributesPrices { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
